### ISSUE TITLE
Pygame_sdl2 error

### ISSUE THREAD

**Issue by fennectech** [uyjulian/renpy-switch#8]
`[fennectech@jasper ~/angels/renpy-switch/pygame_sdl2]$  PYGAME_SDL2_STATIC=1 python setup.py
pygame_sdl2.error is out of date.
Traceback (most recent call last):
  File "setup.py", line 110, in <module>
    cython("pygame_sdl2.error", libs=sdl_libs)
  File "/home/fennectech/angels/renpy-switch/pygame_sdl2/setuplib.py", line 247, in cython
    subprocess.check_call([
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cython'`
 Ive gotten to the pygame part in your building.md guide but ive got this
Could you make it more verbose and provide links to the cpython and pygame we are supposed to use?

**Comment by uyjulian** [comment]
Install cython from pip.

**Comment by fennectech** [comment]
That worked   ive gotten here now 

````[fennectech@jasper ~/angels/renpy-switch/renpy/module]$  RENPY_DEPS_INSTALL=$PORTLIBS_PREFIX RENPY_STATIC=1 python setup.py
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    import generate_styles
  File "/home/fennectech/angels/renpy-switch/renpy/module/generate_styles.py", line 24, in <module>
    str = unicode  # @ReservedAssignment
NameError: name 'unicode' is not defined
````

**Comment by uyjulian** [comment]
Current directory should be in `renpy-switch`  
`pygame_sdl2` should be located at `../pygame_sdl2/`  
Ren'Py should be located at `../renpy/`

**Comment by fennectech** [comment]
do you happen to have discord?  ive got that setup as you said

**Comment by fennectech** [comment]
what about the error in cython file

**Comment by uyjulian** [comment]
Did you checkout version 7.3.5.606 of Ren'Py? There is some ongoing work in Ren'Py that causes breakage with Python 2.

My discord is my username sharp 6810

**Comment by fennectech** [comment]
I did

**Comment by uyjulian** [comment]
Try using python 2 Cython

**Comment by fennectech** [comment]
```[fennectech@jasper ~/angels/renpy-switch/renpy/module]$  RENPY_DEPS_INSTALL=$PORTLIBS_PREFIX RENPY_STATIC=1 python2 setup.py
renpy.gl.gldraw is out of date.
/usr/lib/python2.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/fennectech/angels/renpy-switch/renpy/renpy/gl/gldraw.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: /home/fennectech/angels/renpy-switch/renpy/renpy/gl/gl.pxd:80:8: 'GL_BGRA' redeclared 
renpy.gl2.gl2draw is out of date.
/usr/lib/python2.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/fennectech/angels/renpy-switch/renpy/renpy/gl2/gl2draw.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
renpy.angle.gldraw is out of date.
/usr/lib/python2.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/fennectech/angels/renpy-switch/renpy/renpy/angle/gldraw.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: /home/fennectech/angels/renpy-switch/renpy/renpy/angle/gl.pxd:80:8: 'GL_BGRA' redeclared 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```   Like this?

**Comment by uyjulian** [comment]
Yes, that is correct output.

**Comment by fennectech** [comment]
What dir do i run these in? 
````Use external_library_build/link_sources.bash to link the Pygame_SDL2 and Ren'Py module source files to the correct place.
Use external_library_build/link_compile_pylibs.bash to link and compile the Python, Pygame_SDL2 and Ren'Py module source files to the correct place.````

**Comment by uyjulian** [comment]
Run in the repository folder

**Comment by fennectech** [comment]
I ended up starting over and ran into this    Its probally a package im missing 
```
[fennectech@jasper ~/angels/renpy-switch/cpython-2.7.17/build]$  ../configure LDFLAGS="-specs=$DEVKITPRO/libnx/switch.specs $LDFLAGS" CONFIG_SITE="config.site" --host=aarch64-none-elf --build=$(../config.guess) --prefix="$PORTLIBS_PREFIX" --disable-ipv6 --disable-shared --enable-optimizations
configure: loading site script ./config.site
checking build system type... x86_64-pc-linux-gnu
checking host system type... aarch64-none-elf
checking for python2.7... python2.7
checking for python interpreter for cross build... python2.7
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... horizon
checking EXTRAPLATDIR... 
checking for --without-gcc... no
checking for --with-icc... no
checking for aarch64-none-elf-gcc... no
checking for gcc... gcc
configure: WARNING: using cross tools not prefixed with host triplet
checking whether the C compiler works... no
configure: error: in `/home/fennectech/angels/renpy-switch/cpython-2.7.17/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Whats all needed to compile this?

**Comment by fennectech** [comment]
i started fresh and am running throught he python again  What do i o with this? is it normal?

```[fennectech@jasper ~/angels/renpy-switch/cpython-2.7.17/build]$  make libpython2.7.a
/bin/sh ../Modules/makesetup -c ../Modules/config.c.in \
			-s Modules \
			Modules/Setup.config \
			Modules/Setup.local \
			Modules/Setup
The Makefile was updated, you may need to re-run make.
Makefile:238: *** missing separator.  Stop.

{01:53} Sun Dec 22
[fennectech@jasper ~/angels/renpy-switch/cpython-2.7.17/build]$  make libpython2.7.a
Makefile:238: *** missing separator.  Stop.

```

**Comment by uyjulian** [comment]
Make sure you copied `Setup.local` properly

**Comment by fennectech** [comment]
after the configure i did this 
```
[fennectech@jasper ~/angels/renpy-switch/cpython-2.7.17/build]$  cd Modules/

{13:51} Sun Dec 22
[fennectech@jasper ~/angels/renpy-switch/cpython-2.7.17/build/Modules]$  cp ../../../external_library_build/cpython_config_files/Setup.local Setup.local

{13:51} Sun Dec 22
[fennectech@jasper ~/angels/renpy-switch/cpython-2.7.17/build/Modules]$  cd ..

{13:51} Sun Dec 22
[fennectech@jasper ~/angels/renpy-switch/cpython-2.7.17/build]$  make libpython2.7.a
Makefile:238: *** missing separator.  Stop.

```

**Comment by fennectech** [comment]
FennecTECH#4926 is my user on discord

**Comment by uyjulian** [comment]
Are you using GNU Make or BSD Make?

Copy the entire contents of the `Modules/Setup.local` file itself using `cp`. If you messed with the repository, be sure to check out the original contents by changing directory to CPython repository and `git checkout -- .`

**Comment by fennectech** [comment]
GNU make

**Comment by uyjulian** [comment]
Discussion continues on Discord.

Please e-mail me if you want a copy of the conversation.

**Comment by jexom** [comment]
I've hit exactly the same roadblock when trying to build against RenPy 7.3.5.606, because your latest release has 7.3.5.0, which is low for my existing project.
Something is apparently wrong in the Setup.local file because one of the lines from it gets copied directly into the Makefile unlike other modules
